version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_URL=https://mirnet.site/api
    networks:
      - vpn_network

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/certs:/etc/nginx/certs
  #   depends_on:
  #     - frontend
  #   networks:
  #     - wheelsgo_network

networks:
  vpn_network:
    driver: bridge
